"""create project_expenses table

Revision ID: 3e6b387a0646
Revises: be9864fdfeb0
Create Date: 2025-11-24 22:29:44.274320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e6b387a0646'
down_revision = 'be9864fdfeb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expense_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('document_amount', sa.Numeric(precision=14, scale=2), nullable=True))
        batch_op.add_column(sa.Column('obligation_amount', sa.Numeric(precision=14, scale=2), nullable=True))
        batch_op.add_column(sa.Column('activity_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('reminders', sa.Text(), nullable=True))
        batch_op.drop_column('reminder_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reminder_date', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.drop_column('reminders')
        batch_op.drop_column('activity_date')
        batch_op.drop_column('obligation_amount')
        batch_op.drop_column('document_amount')
        batch_op.drop_column('expense_type')

    # ### end Alembic commands ###
