"""create constructions_contract table

Revision ID: 3e6d4d93bf85
Revises: 65a165120daa
Create Date: 2025-11-21 11:06:54.549938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e6d4d93bf85'
down_revision = '65a165120daa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('construction_contracts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('contractor_name', sa.String(length=255), nullable=False),
    sa.Column('contractor_address', sa.Text(), nullable=True),
    sa.Column('project_name', sa.String(length=255), nullable=False),
    sa.Column('project_site', sa.Text(), nullable=True),
    sa.Column('ntp_date', sa.Date(), nullable=True),
    sa.Column('completion_date', sa.Date(), nullable=True),
    sa.Column('contract_id', sa.String(length=255), nullable=True),
    sa.Column('contract_price', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_id')
    )
    op.create_table('project_expenses',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('contract_id', sa.BigInteger(), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=True),
    sa.Column('item', sa.Text(), nullable=True),
    sa.Column('qty', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('material_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('labor_charge', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('gasoline_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('document_ref', sa.String(length=255), nullable=True),
    sa.Column('obligation_ref', sa.String(length=255), nullable=True),
    sa.Column('activity', sa.String(length=255), nullable=True),
    sa.Column('reminder_date', sa.Date(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['construction_contracts.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_expenses')
    op.drop_table('construction_contracts')
    # ### end Alembic commands ###
