"""add fields column in project_expenses

Revision ID: 442607d26bcb
Revises: 983aa0c30cb8
Create Date: 2025-11-29 17:11:33.861550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '442607d26bcb'
down_revision = '983aa0c30cb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('labor_id', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('rate_per_day', sa.Numeric(precision=14, scale=2), nullable=True))
        batch_op.add_column(sa.Column('days', sa.Numeric(precision=12, scale=3), nullable=True))
        batch_op.create_foreign_key(None, 'employees', ['labor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_expenses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('days')
        batch_op.drop_column('rate_per_day')
        batch_op.drop_column('labor_id')

    # ### end Alembic commands ###
