"""make booking_id and booking_amount nullable in catering_transaction

Revision ID: 485ffa97c53d
Revises: 9a46a683883a
Create Date: 2026-01-20 09:51:00.889647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '485ffa97c53d'
down_revision = '9a46a683883a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catering_transaction', schema=None) as batch_op:
        batch_op.alter_column('booking_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('booking_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catering_transaction', schema=None) as batch_op:
        batch_op.alter_column('booking_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('booking_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
