"""Remove unique constraint from invoice_number

Revision ID: 65936d587cd4
Revises: afd23f16b3f0
Create Date: 2025-11-27 15:15:34.902202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65936d587cd4'
down_revision = 'afd23f16b3f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_invoice_counter', schema=None) as batch_op:
        batch_op.alter_column('last_seq',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('project_expenses', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('project_expenses_invoice_number_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_expenses', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('project_expenses_invoice_number_key'), ['invoice_number'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('daily_invoice_counter', schema=None) as batch_op:
        batch_op.alter_column('last_seq',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))

    # ### end Alembic commands ###


