"""add carenderia_transaction

Revision ID: 786ee4f8936a
Revises: 9dbf4ca9864c
Create Date: 2026-01-14 08:38:52.965792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '786ee4f8936a'
down_revision = '9dbf4ca9864c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carenderia_transaction',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('trans_type', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('carenderia_transaction')
    # ### end Alembic commands ###
