"""remove unique constraint from contract_duration

Revision ID: 8e219b182c8b
Revises: 3e6d4d93bf85
Create Date: 2025-11-24 17:52:26.467231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e219b182c8b'
down_revision = '3e6d4d93bf85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('construction_contracts', schema=None) as batch_op:
        batch_op.alter_column('contract_duration',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('department',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('department',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=150),
               existing_nullable=True)

    with op.batch_alter_table('construction_contracts', schema=None) as batch_op:
        batch_op.alter_column('contract_duration',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
