"""add rate_per_day column

Revision ID: 983aa0c30cb8
Revises: 65936d587cd4
Create Date: 2025-11-28 16:34:19.825949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '983aa0c30cb8'
down_revision = '65936d587cd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rate_per_day', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('rate_per_day')

    # ### end Alembic commands ###
