"""add carenderia_wages

Revision ID: 9dbf4ca9864c
Revises: a1b2c3d4e5f6
Create Date: 2026-01-13 15:26:22.544960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dbf4ca9864c'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carenderia_wages',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('emp_id', sa.BigInteger(), nullable=False),
    sa.Column('emp_name', sa.String(length=150), nullable=False),
    sa.Column('dept_id', sa.BigInteger(), nullable=True),
    sa.Column('emp_role', sa.String(length=100), nullable=True),
    sa.Column('emp_rate', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('menu_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carenderia_daily_summary',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('venture_id', sa.SmallInteger(), nullable=True),
    sa.Column('summary_date', sa.Date(), nullable=False),
    sa.Column('total_sales', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('total_expenses', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_synced', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('venture_id', 'summary_date', name='uix_venture_summary_date')
    )
    op.create_table('carenderia_expenses',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('summary_id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('receipt_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['summary_id'], ['carenderia_daily_summary.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('carenderia_expenses')
    op.drop_table('carenderia_daily_summary')
    op.drop_table('menu_items')
    op.drop_table('carenderia_wages')
    # ### end Alembic commands ###
