"""add invoice_number column

Revision ID: afd23f16b3f0
Revises: 3e6b387a0646
Create Date: 2025-11-25 10:37:02.402146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afd23f16b3f0'
down_revision = '3e6b387a0646'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_number', sa.String(length=50), nullable=True))
        batch_op.create_unique_constraint(None, ['invoice_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_expenses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('invoice_number')

    # ### end Alembic commands ###
