"""add catering_requests table

Revision ID: b3526decd06b
Revises: 0611bad928dd
Create Date: 2025-11-20 10:58:42.765327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3526decd06b'
down_revision = '0611bad928dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catering_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requestor_name', sa.String(length=150), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('event_time', sa.Time(), nullable=False),
    sa.Column('items_requested', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('catering_requests')
    # ### end Alembic commands ###
