"""add catering_transaction table

Revision ID: b9ac27160058
Revises: a7cfdf5891d2
Create Date: 2026-01-19 15:39:33.569806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9ac27160058'
down_revision = 'a7cfdf5891d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catering_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('booking_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('trans_description', sa.String(length=255), nullable=False),
    sa.Column('trans_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['catering_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('catering_transaction')
    # ### end Alembic commands ###
