"""create project_expenses table

Revision ID: be9864fdfeb0
Revises: 8e219b182c8b
Create Date: 2025-11-24 22:21:24.789451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be9864fdfeb0'
down_revision = '8e219b182c8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Fix: project_expenses table was already created in migration 3e6d4d93bf85
    # Check if table exists before creating it
    connection = op.get_bind()
    
    check_table_sql = sa.text("""
        SELECT EXISTS (
            SELECT 1 
            FROM information_schema.tables 
            WHERE table_schema = 'public' 
            AND table_name = 'project_expenses'
        )
    """)
    result = connection.execute(check_table_sql)
    table_exists = result.scalar()
    
    if not table_exists:
        # Table doesn't exist, create it
        op.create_table('project_expenses',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('contract_id', sa.BigInteger(), nullable=False),
        sa.Column('expense_date', sa.Date(), nullable=True),
        sa.Column('item', sa.Text(), nullable=True),
        sa.Column('qty', sa.Numeric(precision=12, scale=3), nullable=True),
        sa.Column('unit', sa.String(length=50), nullable=True),
        sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column('material_amount', sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column('labor_charge', sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column('gasoline_amount', sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column('document_ref', sa.String(length=255), nullable=True),
        sa.Column('obligation_ref', sa.String(length=255), nullable=True),
        sa.Column('activity', sa.String(length=255), nullable=True),
        sa.Column('reminder_date', sa.Date(), nullable=True),
        sa.Column('created_by', sa.BigInteger(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['contract_id'], ['construction_contracts.id'], ),
        sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
    # else: table already exists, skip creation
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_expenses')
    # ### end Alembic commands ###
