"""modify catering request model

Revision ID: ee24f4701032
Revises: 786ee4f8936a
Create Date: 2026-01-15 20:25:54.080019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee24f4701032'
down_revision = '786ee4f8936a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catering_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_address', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('contact_number', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('email_address', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catering_requests', schema=None) as batch_op:
        batch_op.drop_column('email_address')
        batch_op.drop_column('contact_number')
        batch_op.drop_column('customer_address')

    # ### end Alembic commands ###
